# Generated by Django 5.0.3 on 2024-03-04 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField()),
                ('investment_purpose', models.CharField(max_length=100)),
                ('investment_knowledge', models.CharField(max_length=100)),
                ('investment_horizon', models.CharField(max_length=100)),
                ('risk_tolerance', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_product', models.TextField(max_length=200)),
                ('ticker', models.TextField(max_length=200)),
                ('provider', models.TextField(max_length=200)),
                ('brief_description', models.TextField(max_length=500)),
                ('expected_return', models.TextField(max_length=200)),
                ('composition', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='robo_advisor_app.questionnaire')),
                ('response', models.ManyToManyField(to='robo_advisor_app.response')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='robo_advisor_app.user'),
        ),
    ]
