# Generated by Django 5.0.3 on 2024-03-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo_advisor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
